name: trigger jenkins job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "INT-3100-azure-remediation-onboarding" ] #todo - delete branch

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: ${{ secrets.JENKINSURL }}
        user: ${{ secrets.JENKINSUSER }}
        token: ${{ secrets.JENKINSTOKEN }}
        job: ${{ secrets.JENKINSJOBNAME }}