name: azure update zip on commit
on:
  push:
    branches: [ "master", "INT-3100-azure-remediation-onboarding" ] #todo - delete branch

  workflow_dispatch:

jobs:
  deploy:
    name: upload to Amazon s3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Copy and zip files to s3
        run: |
          pwd=`pwd`
          uploadFolder="upload"
          echo {{secrets.FILELOCATION}}
          
